from django.db import transaction
from django.core.exceptions import ValidationError
from appointments.models import Appointment
from .models import Symptom, PreVisitSummary, Consultation, Prescription, Medication, PostVisitSummary
from ai.ai_service import analyze_symptoms, generate_patient_summary

@transaction.atomic
def trigger_pre_visit_summary(appointment_id):
    """
    Triggers AI symptom analysis and saves PreVisitSummary.
    Ensures Gemini failure does not break the booking transaction.
    """
    try:
        appointment = Appointment.objects.get(id=appointment_id)
    except Appointment.DoesNotExist:
        return None

    # Retrieve symptom text
    symptom_obj = getattr(appointment, 'symptoms', None)
    if not symptom_obj:
        return None

    symptoms_text = symptom_obj.symptoms_text

    # Default placeholder values in case of failure
    summary_obj, created = PreVisitSummary.objects.get_or_create(
        appointment=appointment,
        defaults={
            'urgency': PreVisitSummary.Urgency.UNAVAILABLE,
            'chief_complaint': "AI summary is temporarily unavailable. Please review the patient's original symptoms.",
            'suggested_questions': [],
            'status': 'PENDING'
        }
    )

    try:
        result = analyze_symptoms(symptoms_text)
        summary_obj.urgency = result['urgency']
        summary_obj.chief_complaint = result['chief_complaint']
        summary_obj.suggested_questions = result['suggested_questions']
        summary_obj.status = 'COMPLETED'
        summary_obj.save()
    except Exception as e:
        print(f"[Pre-Visit Summary Error] Failed to generate AI summary for appointment {appointment_id}: {e}")
        summary_obj.status = 'UNAVAILABLE'
        summary_obj.urgency = PreVisitSummary.Urgency.UNAVAILABLE
        summary_obj.chief_complaint = "AI summary is temporarily unavailable. Please review the patient's original symptoms."
        summary_obj.save()

    return summary_obj


@transaction.atomic
def create_consultation(appointment_id, doctor_notes, follow_up_date, medications):
    """
    Saves consultation, prescription, medications, and triggers AI post-visit patient summary.
    Sets appointment status to COMPLETED.
    """
    try:
        appointment = Appointment.objects.select_for_update().get(id=appointment_id)
    except Appointment.DoesNotExist:
        raise ValidationError("Appointment not found.")

    if appointment.status != Appointment.Status.CONFIRMED:
        raise ValidationError("Only confirmed appointments can be completed.")

    # Create Consultation
    consultation = Consultation.objects.create(
        appointment=appointment,
        doctor_notes=doctor_notes,
        follow_up_date=follow_up_date
    )

    # Update appointment status
    appointment.status = Appointment.Status.COMPLETED
    appointment.save()

    # Create Prescription
    prescription = Prescription.objects.create(consultation=consultation)

    # Create Medications
    medication_instances = []
    for med in medications:
        med_obj = Medication.objects.create(
            prescription=prescription,
            medicine_name=med['medicine_name'],
            dosage=med['dosage'],
            frequency=med['frequency'],
            duration=med['duration'],
            instructions=med.get('instructions', '')
        )
        medication_instances.append(med_obj)

    # Create PostVisitSummary placeholder
    summary_obj = PostVisitSummary.objects.create(
        consultation=consultation,
        summary="Summary is generating...",
        status='PENDING'
    )

    # Trigger patient-friendly AI summary (wrapped in nested try-catch so failure is non-blocking)
    try:
        summary_text = generate_patient_summary(doctor_notes, medications)
        summary_obj.summary = summary_text + "\n\nWarning: This summary is for informational purposes only. It is generated by AI and does not replace professional medical judgment."
        summary_obj.status = 'COMPLETED'
        summary_obj.save()
    except Exception as e:
        print(f"[Post-Visit Summary Error] Failed to generate AI post-visit summary: {e}")
        # Save fallback summary
        meds_text = ", ".join([f"{m['medicine_name']} ({m['dosage']})" for m in medications])
        fallback_text = (
            f"Consultation Summary:\n"
            f"Notes: {doctor_notes}\n"
            f"Prescriptions: {meds_text}\n\n"
            f"Note: AI summary is temporarily unavailable. Please refer to the doctor's notes and prescription details above."
        )
        summary_obj.summary = fallback_text
        summary_obj.status = 'FAILED'
        summary_obj.save()

    # Queue medication reminders
    try:
        from notifications.services import schedule_medication_reminders
        schedule_medication_reminders(prescription.id)
    except Exception as e:
        print(f"Medication reminder scheduling failed: {e}")

    # Queue post-visit notification
    try:
        from notifications.services import queue_post_visit_notifications
        queue_post_visit_notifications(appointment.id)
    except Exception as e:
        print(f"Post-visit notification failed: {e}")

    return consultation
