# Generated by Django 6.1 on 2026-08-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctorworkinghours',
            name='unique_doctor_working_day',
        ),
    ]
